#!/bin/sh -e

# checking hockeyeth account

uid=`getent passwd hockeyeth | cut -d ":" -f 3`
home=`getent passwd hockeyeth | cut -d ":" -f 6`

# if there is the uid the account is there and we can do
# the sanit(ar)y checks otherwise we can safely create it.

if [ "$uid" ]; then
	# guess??? the checks!!!
	if [ $uid -ge 100 ] && [ $uid -le 999 ]; then
		echo "hockeypuck uid check: ok"
	else
		echo "ERROR: hockeypuck account has a non-system uid!"
		exit 1
	fi
	if [ "$home" = "/var/lib/hockeypuck" ]; then
		echo "hockeypuck homedir check: ok"
	else
		echo "ERROR: hockeypuck account has an invalid home directory!"
		exit 1
	fi
else
	# what this might mean?? oh creating a system l^Huser!
	adduser --quiet \
			--system \
			--disabled-password \
			--home /var/lib/hockeyeth \
		--shell /bin/bash \
		--group \
		hockeyeth
fi

if [ "$2" = "" ]; then
	# ch{owning,moding} things around
	mkdir -p /var/log/hockeyeth
	chown -R hockeyeth:hockeyeth /var/log/hockeyeth
	chmod -R 755 /var/log/hockeyeth
	find /var/log/hockeyeth -type f -exec chmod 644 '{}' ';'

	chgrp -R adm /var/log/hockeyeth
	chmod	g+s  /var/log/hockeyeth

	mkdir -p /var/lib/hockeyeth
	chown -R hockeyeth:hockeyeth /var/lib/hockeyeth
fi

#DEBHELPER#

exit 0
